"""Create initial tables

Revision ID: ff8da24de7c7
Revises: c6ec858e956c
Create Date: 2025-08-27 18:29:40.277815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ff8da24de7c7"
down_revision: Union[str, None] = "c6ec858e956c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "todo",
        sa.Column("itemid", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("itemid"),
    )
    op.create_table(
        "user",
        sa.Column("userid", sa.Integer(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role"],
            ["role.name"],
        ),
        sa.PrimaryKeyConstraint("userid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("todo")
    op.drop_table("role")
    # ### end Alembic commands ###
